
version: '3'
services:

  game:
    build: game/
    environment:
      - WEBSERVER_PORT=1337
      - PUB_PORT=5555
      - INFERER_HOST=inferer
      - INFERER_PORT=1337
      - PYTHONASYNCIODEBUG=1
    links:
      - inferer
    ports:
      - "1337:1337"

  learner:
    build: learner/
    environment:
      - SUB_HOST=game
      - SUB_PORT=5555
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - game
      - redis

  redis:
    image: redis

  inferer:
    build: inferer/
    environment:
      - WEBSERVER_PORT=5555
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
