
version: '3'
services:

  game:
    build: game/
    environment:
      - WEBSERVER_PORT=5555
      - PUB_PORT=5555
      - INFERER_HOST=inferer
      - INFERER_PORT=1337
    links:
      - normaliser

  learner:
    build: learner/
    environment:
      - GAME_HOST=game
      - GAME_PORT=5555
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - simulator

  redis:
    image: redis

  inferer:
    build: inferer/
    environment:
      - WEBSERVER_PORT=5555
      - REDIS_HOST=redis
      - REDIS_PORT=6379
